# Generated by Django 3.2.9 on 2021-12-24 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_alter_greeting_when'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('actorId', models.AutoField(primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=100)),
                ('lname', models.CharField(max_length=100)),
                ('gender', models.IntegerField(choices=[(0, 'Male'), (1, 'Female')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'movie_actors',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('genreId', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'genre',
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('movieId', models.AutoField(primary_key=True, serialize=False)),
                ('movieTitle', models.CharField(max_length=200)),
                ('movieYear', models.DateField(default='2021-12-12')),
                ('movieLanguage', models.CharField(choices=[('English', 'English'), ('kinyarwanda', 'kinyarwanda'), ('French', 'French')], max_length=200)),
                ('movieLogo', models.ImageField(upload_to='img/%y')),
                ('movie_file', models.FileField(upload_to='img/%y')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('movieActor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello.actor')),
                ('movieGenre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello.genre')),
            ],
            options={
                'db_table': 'movies',
            },
        ),
    ]
